### ISSUE TITLE
Drosophila 1.5 extra-core usage

### ISSUE THREAD

**Issue by tpoppins** [gustafullberg/drosophila#1]
Testing at CCRL turned up a bug in Drosophila's CPU usage.

At startup it grabs one CPU core and "sits on it". On the 12-core dual Xeon I'm typing this it translates into constant 8% CPU usage (i.e. one CPU core occupied), as seen in the Task Manager. When it's the opponent's turn to move it's 8%; when it's Drosophila's turn to move it goes up to 17% (= 2 cores). 

Once Drosophila makes a move, its CPU usage goes back to 8%. With Ponder ON set in GUI (Cute Chess) Drosophila's CPU usage stays at 17% throughout the game. It doesn't look like Drosophila does anything with that first core it constantly "uses", that's why I said "sits on it".

Additionally, it doesn't seem to accept any commands in console mode. An examination of the exec reveals that it supports various XBoard commands, like protover, computer, memory, easy etc., but once you start the engine it won't let you enter any of them. This may have something to do with the bug described above.

edit: Exec used is drosophila-15-win64.exe on Win 7 x64 Pro, console mode as well as Cute Chess GUI (Feb 3 dev build).
A clarification is needed whether Drosophila is indeed a non-SMP engine (= never uses more than one core in its search) or if it in fact does use the extra core it grabs at startup in its search.

**Comment by gustafullberg** [comment]
Thanks for finding and reporting this issue!

It seems to be a problem with the non-blocking reading of stdin on Windows. One CPU-core is basically wasted on just checking if there is any new input data (Xboard command) to process. I can assure you that all searches are single-core (non-SMP).

Drosophila is developed on Linux, so the Windows builds are unfortunately somewhat less well-tested.

I'll post here when I have an fix ready.

**Comment by gustafullberg** [comment]
I fixed the issue with the excess CPU usage on Windows and released [Drosophila 1.5.1](https://github.com/gustafullberg/drosophila/releases/download/v1.5.1/drosophila-1.5.1.zip).
I plan on fixing the other issue (engine not accepting commands in console mode) in version 1.6.

Thanks.
